site_name: Project Elephant Documentation
theme:
  name: material
  palette: 
    primary: teal
    accent: purple

# This allows you to organize your pages in the sidebar
nav:
  - Home: index.md
  - Introduction: introduction.md # You will need to create this file in the docs/ folder