site_name: My Project Docs
theme:
  name: material
  palette: 
    primary: teal
    accent: purple

# This allows you to organize your pages in the sidebar
nav:
  - Home: index.md
  - Guide: guide.md # You will need to create this file in the docs/ folder